Fix compilation error with Win32 GUI.
A "gui/win32/wincfg.c:59: error: static declaration of 'gui_conf' follows
non-static declaration"  occurred because gui_conf recently was changed
'extern'.

Patch by Stephen Sheldon, sfsheldo gmail com.